### ISSUE TITLE
[PE-D][Tester C] Details are truncated when data is long

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T09-4/tp#140]
![image.png](https://raw.githubusercontent.com/junianob/ped/main/files/18e5694f-9e9f-4f89-9887-b79be982f463.png)

Information is cut off when the length is too long.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: junianob/ped#10

**Comment by tituswe** [comment]
Limit name to 50 char
