### ISSUE TITLE
[PE-D][Tester B] "undo redo" is somehow an accepted command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T09-4/tp#155]
"undo redo" is somehow an accepted command but it is not documented. only undo is considered.

same for  "redo undo". only redo is applied.

somehow i can put many "undo" and "redo" separated by whitespace as an accepted command.

![image.png](https://raw.githubusercontent.com/iapetusbob/ped/main/files/a0ee6c14-e9a2-468d-8202-91246a2b1c73.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: iapetusbob/ped#7

**Comment by pangrwa** [comment]
Similar to issue #156
