### ISSUE TITLE
[PE-D][Tester B] cannot see error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T09-4/tp#158]
error message cut off

![image.png](https://raw.githubusercontent.com/iapetusbob/ped/main/files/1c64d725-693f-4f96-a593-f6daa5f45a97.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: iapetusbob/ped#10

**Comment by tituswe** [comment]
should be able to see, idk why he cannot scroll

**Comment by tituswe** [comment]
FIXED: Changed ResultDisplay text alignment to left.

Restriction from JavaFX as there is a bug where the text area doesn't resize with the window aspect ratio.

Helps with user readability
